iso8583 {
  log.path = "./test-logs/"
  db.path = "./data/corner-test.db"
  offset.db.path = "./data/offset-corner.db"
  bindplane.url = "http://localhost:4318/v1/metrics"
  correlation.expiration.minutes = 2
  export.interval.seconds = 2
  watch.enabled = true
}
