iso8583 {
  log.path = "./sample-data/"
  db.path = "./data/correlation-test.db"
  offset.db.path = "./data/file_offsets-test.db"
  bindplane.url = "http://localhost:4318/v1/metrics"
  correlation.expiration.minutes = 60
  export.interval.seconds = 2
  watch.enabled = false
}
